### ISSUE TITLE
Add Europe/Kyiv timezone

### ISSUE THREAD

**Issue by bondarenko09** [marnusw/date-fns-tz#120]
Here in Ukraine, we have an online campaign called `#KyivNotKiev` started by our Ministry of Foreign Affairs. For more information you can visit [this article](https://en.wikipedia.org/wiki/KyivNotKiev). Here is official [proof](https://www.timeanddate.com/time/zone/ukraine/kyiv) on timezone name.

Please add a possibility to use `Europe/Kyiv` name for timezone along with `Europe/Kiev`.

Currently I'm getting an error:

![image](https://user-images.githubusercontent.com/54590806/116392159-c740c100-a828-11eb-9570-5386eda89ff2.png)

**Comment by marnusw** [comment]
This library does not have bundled time zone data. If the timezone is not supported that is most likely because the platform/browser you are running it on does not support the timezone in the Intl API. If that is the case you will need to find a polyfill that does support it or substitute a supported zone with a similar offset. You could also open support tickets with the relevant platforms to have their Intl implementations extended.

Please close this issue unless you still believe this is an issue relating to this library.

**Comment by bondarenko09** [comment]
> This library does not have bundled time zone data. If the timezone is not supported that is most likely because the platform/browser you are running it on does not support the timezone in the Intl API. If that is the case you will need to find a polyfill that does support it or substitute a supported zone with a similar offset. You could also open support tickets with the relevant platforms to have their Intl implementations extended.
> 
> Please close this issue unless you still believe this is an issue relating to this library.

**Comment by dmitrylen-fieldpulse** [comment]
use 
```
const isTimeZoneSupported = (tz: string): boolean => {
  try {
    new Intl.DateTimeFormat('en-US', { timeZone: tz });
    return true;
  } catch (e) {
    return false;
  }
};
```
