### ISSUE TITLE
Why would zonedTimeToUtc fail when date string has `Z` in it? 

### ISSUE THREAD

**Issue by Anenth** [marnusw/date-fns-tz#126]
Why would zonedTimeToUtc fail when the date string has `Z` in it? 
When I Call `zonedTimeToUtc('2014-06-25T10:00:00.123Z')` the function just return `2014-06-25T10:00:00.123Z` but if I pass 2014-06-25T10:00:00.123 then it return correctly.

```
// Test 1 - This works fine
it('returns the UTC time of the date in the time zone for a string and IANA tz', function () {    
	var result = zonedTimeToUtc('2014-06-25T10:00:00.123', 'America/Los_Angeles')    		 
    assert.deepEqual(result.toISOString(), '2014-06-25T17:00:00.123Z')  })
})

// Test 2 - This will fail
it('returns the UTC time of the date in the time zone for a string with z and IANA tz', function () {    
	var result = zonedTimeToUtc('2014-06-25T10:00:00.123Z', 'America/Los_Angeles')    		 
    assert.deepEqual(result.toISOString(), '2014-06-25T17:00:00.123Z')  })
})
```

**Comment by marnusw** [comment]
I haven't looked at the code for a while so can't give a quantative answer, but the qualitative answer is that you're telling the function "here is a date string which is in `America/Los_Angeles` time, convert it to my local / proper UTC time", but then it isn't because the `Z` indicates that this date string already represents UTC time. That just doesn't make sense.

If this is a UTC date string from a server which you want to display in the users own timezone you don't need this library at all, just use `parseJSON` from `date-fns`. If you need to display it in a specific timezone then use `utcToZonedTime` and render the resulting date using `format` from this library.

If a user has chosen a date in the client app using a date picker along with a timezone and you need to convert that to the proper UTC time to send to your server, then pass the `Date` instance from the picker directly to `zonedTimeToUtc` along with the timezone.
