### ISSUE TITLE
toDate timezone not setting up and picking the local always

### ISSUE THREAD

**Issue by nitish5808** [marnusw/date-fns-tz#128]
I tried to pass the timezone into toDate as an option to get the time for that zone
`const nyDate = toDate('2021-06-29T08:33:42.239Z', { timeZone: 'America/New_York' })`
`console.log(nyDate + " "); // 2014-10-25 13:46:20+07:00`

but what I get always is the local timezone in console printed, I checked in every browser is the same
`Tue Jun 29 2021 14:03:42 GMT+0530 (India Standard Time) `

**Comment by hdoan-codaio** [comment]
+1. Running into the same issue. Even the example included in the README doesn't work

```
  const bangkokDate = dateFnsTz.toDate('2014-10-25T13:46:20', {timeZone: 'Asia/Bangkok'});
  console.log('bangkok', dateFnsTz.format(bangkokDate, 'yyyy-MM-dd HH:mm:ssxxx', {timeZone: 'Asia/Bangkok'})); 
 // bangkok 2014-10-24 23:46:20+07:00 instead of 2014-10-25 13:46:20+07:00
```

**Comment by marnusw** [comment]
The behaviour you describe is correct. When you call `toDate` with the time zone passed it will return a date with the proper internal UTC time. For example, from the unit tests:

```js
const result = toDate('2014-10-25T13:46:20', { timeZone: 'Asia/Bangkok' })
assert.deepEqual(result, new Date('2014-10-25T13:46:20+07:00'))
```

The above is the first step in what you are trying to achieve. 

Next, you want to display the date, with the internal UTC time / timestamp which stands apart from any time zone, as if the `Date` is for the `Asia/Bangkok` time zone.

That is precisely the primary problem this library intends to solve. If you just log the value of this date it will be in your local time because JavaScript always displays the date in local time. To get the proper output use:

```js
const bangkokDate = utcToZonedTime(result, 'Asia/Bangkok')  // This actually changes the internal timestamp of the date
format(date, 'yyyy-MM-dd HH:mm:ssxxx', { timeZone: 'Asia/Bangkok' }) // The tz not actually necessary here, since not using z..zzzz tokens
```

That should log out `2014-10-25 13:46:20+07:00`.

So the purpose of `toDate` is to convert from a string date without time zone information to a `Date` with the correct timestamp.
The purpose of `utcToZonedTime` and `format` is to display that date for a specific time zone.
