### ISSUE TITLE
Question. zonedTimeToUtc and DST finish point

### ISSUE THREAD

**Issue by ademchenko** [marnusw/date-fns-tz#140]
At the moment the DST time finishes one hour is subtracted from the current local time. That causes repeating of some local points of time twice. For instance, in the case of "Europe/Paris" time zone "2021-10-31 02:10:00" happens twice.
So, I'm just wondering if there's a guarantee that any code similar to  the following one (but for other timezones and DST finish points)
```
require("date-fns/package.json"); // date-fns is a peer dependency. 
var dateFnsTz = require("date-fns-tz")
dateFnsTz.zonedTimeToUtc("2021-10-31 02:10:00", 'Europe/Paris')
```
will **always** return the second (last) repeating point of time, i.e. in that case it will return "2021-10-30 01:10:00" UTC time but not "2021-10-31 00:10:00" UTC. 

Of course, I have run that example and it works as expected. But some other libs state that their behaviour is not specified - like in one case they are free to return the second repeating point, but for another timezone and year - the first repeating point. So, that's why I decided to ask if zonedTimeToUtc is consistent from zone to zone.

**Comment by marnusw** [comment]
The simple answer is I'm not sure because I haven't tested it. So in that sense it is also unspecified. I would imagine that it would work the same in each hemisphere, though. i.e. whatever you get in Paris will probably also happen in Russia, and the same with East / West Coast time in the US. That is if there is a difference between the hemispheres. There is nothing I can think of which would make the outcome vary randomly. (But I'm still not guaranteeing that.)
