### ISSUE TITLE
Incorrect time for given timeZone

### ISSUE THREAD

**Issue by saiumesh-letznav** [marnusw/date-fns-tz#15]
Thanks for Awesome library!

While converting from string date to required timezone, is giving wrong time.

**Date string is in UTC**

`utcToZonedTime('2019-03-20 10:51:43', 'America/New_York');`
expected value is **03-20-2019 06:52**
actual value is **03-20-2019 01:21**

we were using moment before, as shown below, and it gives expected result
`moment.utc(date).tz(timeZone)`

Thanks!!

**Comment by marnusw** [comment]
The reason is that a derivative of `toDate` from `date-fns` is used to convert that string to a `Date`. When the input string is in ISO format it works fine, because that makes it clear that the provided date is at UTC time. In your case the date is assumed to be in the local time zone (as JS normally would) of which the UTC will be some other values; the offset added by `utcToZonedTime` then works on this incorrect value. It is the equivalent of `moment(date).tz(timeZone)`.

While I've never used this library with non-ISO date strings I can see that the expectation might be for it to work as you expected, which would be to assume that any date string in a any format would represent UTC time (unless, I guess, there is a time offset portion in the string itself). I need some time to think this over, because for one `date-fns@2.0.0-alpha.27` removed automated string persing from their `toDate` function (and all others by extension), it is now required to use `parse()` or `fromISO()`.

That said, your problem is also not really parsing the string, but rather specifying a time zone along with parsing, e.g. `parse(date, 'yyyy-MM-dd HH:mm:ss', {timeZone: 'UTC'})`. That would equate to `moment.utc(date)`. Thereafter `utcToZonedTime` would work as expected if you did `utcToZonedTime(parsedDateAtUTC, 'America/New_York')`.

Maybe that is the answer. It would match the new way of doing things in `date-fns`, which it should, and simply be an extension of their `parse` function which also accepts the `timeZone` options, similar to the extended `format` function. I imagine `parse` could then ignore all time zone related components in the date string if a `timeZone` option is provided.

Before `parse` was not implemented because it won't be possible to parse the long/short time zone names, but this is an extension that would make a lot of sense.

I'll do some more thinking on this, and would also welcome your thoughts.

In the meantime, I wonder if it might work if you just append `Z` to the end of the date string when you pass it to `utcToZonedTime`. I'm just taking a random stab here, but it's quite possible `toDate` would then handle it correctly. It's a bit of a hack, but perhaps an acceptable one in the meantime.

**Comment by benmccann** [comment]
Adding a time zone to `parse` makes sense to me. There's some question of what happens if the string to be parsed specifies a time zone and the user separately specifies the time zone option. Throw an exception? Or make one take precedence over the other? It looks like luxon has the date string take precedence: https://moment.github.io/luxon/docs/class/src/datetime.js~DateTime.html#static-method-fromFormat

**Comment by marnusw** [comment]
Thank you for sharing your thoughts @benmccann. I have started adjusting the library to make it more in line with the `date-fns` changes introduced in `alpha.27`. I will include `parse` in this new major version since `toDate` should not accept strings anymore.

@saiumesh-letznav after looking at the `date-fns-tz` code again (it's been a while) I realised you can use `toDate` from the current version to get the result you need:

```js
import { toDate, utcToZonedTime } from 'date-fns-tz'

const utcDate = toDate('2019-03-20 10:51:43', { timeZone: 'UTC' });
const zonedDate = utcToZonedTime(utcDate, 'America/New_York');
format(zonedDate, 'dd-MM-yyyy HH:mm:ss z', { timeZone: 'America/New_York' }

// Should give 03-20-2019 06:51:43 EDT
```

**Comment by saiumesh-letznav** [comment]
Thank you so much @marnusw  and @benmccann I was able to get expected time. you are awesome. 👌
