### ISSUE TITLE
zonedTimeToUtc

### ISSUE THREAD

**Issue by narviii** [marnusw/date-fns-tz#16]
cannot make it work, doesn't load

**Comment by marnusw** [comment]
@narviii this is not at all constructive. Presumably the library works because it sees many downloads without complaints and I also use it myself in various projects.

While I cannot commit to helping you integrate this into your project, if you would provide a proper description of the issue you are seeing then I might look in to it and offer assistance; otherwise this issue is best closed.

While this project doesn't offer an issue template I urge you to look at the issue templates of some other major libraries and submit something similarly descriptive.

Thanks.
