### ISSUE TITLE
zonedTimeToUtc should ignore timezone if provided one

### ISSUE THREAD

**Issue by nhannah** [marnusw/date-fns-tz#165]
https://github.com/marnusw/date-fns-tz/commit/96032268d3bed81256a8db18cdfdfc2c0d390be9

Changed the functionality of `zonedTimeToUtc` so that if a timestamp with a `Z` was provided it would now not work properly.

2022-02-04T01:00:00.000Z with timezone request of UTC in MST zone returns 2022-02-03T18:00:00.000Z, it should return itself as a date.

**Comment by marnusw** [comment]
Will you please provide some code showing what you wish to achieve so it's easier for me to grok quickly? Also please confirm that this worked in the last version published before the commit you've sited.

**Comment by nhannah** [comment]
Hi, yes, I don't love what this function was doing in our code, it was inherited, but to sum it up.
`zonedTimeToUtc(stamp, zone)`
let's say that ends up being:
`zonedTimeToUtc('2022-02-04T01:00:00.000Z', 'UTC')`
in essence this is redundant but possible, previously it would return a new Date at `2022-02-04T01:00:00.000Z`.
After the commit noted `zonedTimeToUtc('2022-02-04T01:00:00.000Z', 'UTC')` returns a Date at UTC as though the zoned date is local, i.e. if you are in MST `zonedTimeToUtc('2022-02-04T01:00:00.000Z', 'UTC')` now returns `2022-02-03T18:00:00.000Z`

**Comment by marnusw** [comment]
The current functionality after the commit in question is as intended. 

`zonedTimeToUtc` converts a date that **displays** correctly in your local time _back_ to a proper date instance with a meaninful equivalent UTC time. In your case `new Date('2022-02-04T01:00:00.000Z')` will result in a displayed date depending on the system time zone, and as such the output will also depend on the system time zone, which is what it is suppoed to do.

Whenever you work with ISO date strings, you most likely have no need for this library, because you are working with absolute moments in time independent of time zone. Since you already have `'2022-02-04T01:00:00.000Z'` you should just use that and drop the redundant (and previously incorrect, now infeasible) use of `zonedTimeToUtc` entirely.

The *(only?)* reason to use this library is to display or take as input a date to/from a user in a specific time zone instead of their system time zone, and it doesn't sound like that's what you are doing. Othewise, as I've said, I'm not understanding your usecase and proving me with sample code of what you are trying to achive might help with that.

**Comment by nhannah** [comment]
You are 100% correct, we are no longer using this, and I believe it was meant in the past for some dirty data scenarios. But it still seems to me the commit in question changes the functionality significantly.

In the past this function assumed any ISO string passed in is already correct. Now it assumes an ISO string passed in is erroneous and should be adjusted as you really want that date/time in your timezone then adjusted to UTC. It seems to me this functionality should be chosen via a parameter if anything as functionally these 2 scenarios are both valid and different.

**Comment by marnusw** [comment]
You can't change a full ISO UTC time string, it's the equivalent of a timestamp. The only thing that makes sense to change is how that time is displayed in a specific given time zone. Therefore the current functaionlity makes sense. If you have the correct ISO string, you're done. If you want to parse an arbitrary date string without time zone information, i.e. without the `Z`, then using `date-fns#parse` and `zonedTimeToUtc` subsequently is the correct solution.

I admit the functionality changed, and that should only happen in a major version release; however, it's too late now and since this is an edge case which should never have worked there won't be any further changes made.

Thank you for your input, though, and I'm glad your code is working now.
