### ISSUE TITLE
Possible support for ".formatDistance()"?

### ISSUE THREAD

**Issue by santospatrick** [marnusw/date-fns-tz#17]
Would this library support [.formatDistance()](https://date-fns.org/v2.0.0-alpha.27/docs/formatDistance) in the future? I personally use this function with i18n for "pt" language and i need to get timezone with `new Date().getTimezoneOffset() / 60` but i dont know when do i need to `sum` or `subtract` from current time given to me from back end as ISO Format. Does this lib will sum or subtract hours (when formatting with `.formatDistance()`), automatically?

**Comment by marnusw** [comment]
I'm not sure that this library will have to support `formatDistance` in order for this to work. The main problem is that JS will always give you a date in the local time of the machine it runs on. This is overcome by using the `utcToZonedTime` and `zonedTimeToUtc` rather than `new Date` and `toISOString` directly. The only reason `format` also needs to be extended is to add the `z..zzzz` tokens. Couldn't you just use the date-fns `formatDistance` function client side after applying `utcToZonedTime` to the ISO date you receive from the server?

**Comment by santospatrick** [comment]
@marnusw thanks for answering. I will give it a try and come back with some code tomorrow.
