### ISSUE TITLE
CommonJS or AMD dependencies can cause optimization bailouts warning in Angular 12

### ISSUE THREAD

**Issue by ionut-t** [marnusw/date-fns-tz#183]
I'm using the `date-fns-tz` library, version 1.3.4, in an Angular project (v12) and the compiler throws a warning because it seems is not an ECMAScript module. In my Angular project, I can make that warning disappear, but I prefer not to do that yet.

```some.component.ts depends on 'date-fns-tz'. CommonJS or AMD dependencies can cause optimization bailouts```

The same issue was reported and fixed for the `date-fns` library, reference [#2404](https://github.com/date-fns/date-fns/issues/2404).

I'm quite happy using this library and I hope this issue will be fixed.

**Comment by marnusw** [comment]
Happy to take a look when I can. If you need this quickly pleaes submit a PR.

**Comment by ionut-t** [comment]
Hi @marnusw, thanks for looking into it.

I had a look at the source code and I've noticed that the functions are exported defaults and I had to use them as such instead of as exported modules and by doing that, the warning goes away. 

Basically, `import zonedTimeToUtc from 'date-fns-tz/zonedTimeToUtc'` instead of `import { zonedTimeToUtc } from 'date-fns-tz'`.

Maybe this issue can be closed if this is the behaviour intended but also maybe a note should be added to the documentation.

**Comment by marnusw** [comment]
It looks like you were seeing that warning precisely because you **were** importing CommonJS files, while your Angular project is most likely looking for ESM imports. Try using `import { zonedTimeToUtc } from 'date-fns-tz'/esm`. There is a comment about this [in the docs](https://github.com/marnusw/date-fns-tz#esm-and-commonjs).

**Comment by urielzen** [comment]
I did as suggested but I get the following error.

```
 Could not find a declaration file for module 'date-fns-tz/esm'. 
'C:/xxx/node_modules/date-fns-tz/esm/index.js' implicitly has an 'any' type. 
```

Which I can make go away by adding a `@ts-ignore` above the `import`

```typescript
// @ts-ignore
import { utcToZonedTime } from 'date-fns-tz/esm';
```

But I thought you should know  😉

**Comment by marnusw** [comment]
Thanks for the note. I'll look into that when I can.

**Comment by vamshidhar-cb** [comment]
If i use below code 
`// @ts-ignore
import { utcToZonedTime } from 'date-fns-tz/esm';`

i am getting below error
`./src/app/app.component.ts:48:18-34 - Error: export 'default' (imported as 'formatInTimeZone') was not found in 'date-fns-tz/esm' (possible exports: format, formatInTimeZone, getTimezoneOffset, toDate, utcToZonedTime, zonedTimeToUtc)`

**Comment by Syritchenko** [comment]
> Even i use esm import like `import formatInTimeZone from 'date-fns-tz/esm/formatInTimeZone'`
> 
> i am getting below error `Warning: C:\Users\vamsh\Desktop\Angular-test\my-app\node_modules\date-fns-tz\esm\formatInTimeZone\index.js depends on 'date-fns/_lib/cloneObject/index.js'. CommonJS or AMD dependencies can cause optimization bailouts. For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies ` i have tried different solutions, but no luck

same issue

**Comment by tegola** [comment]
Same issue here, using `import { utcToZonedTime, zonedTimeToUtc } from 'date-fns-tz/esm'` I get the following warnings:

```
Warning: /usr/src/app/node_modules/date-fns-tz/esm/format/index.js depends on 'date-fns/format/index.js'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: /usr/src/app/node_modules/date-fns-tz/esm/formatInTimeZone/index.js depends on 'date-fns/_lib/cloneObject/index.js'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
```

**Comment by marnusw** [comment]
`date-fns` does not support modern ESM exports. Until they do, the only way to get `date-fns-tz` to work is to import their CJS modules, otherwise it complains about importing a non `type: module` project into one. Please apply pressure in the `date-fns` project to support ESM. (I believe they do intend to in v3.) The only alternative would be to copy the ESM files from `date-fns` into `date-fns-tz`, but that doesn't seem ideal, especially copying the large `format` function. Please share if anyone has another idea how we can make this work or if you think I'm missing something.
