### ISSUE TITLE
utcToZonedTime "works" with imaginary time zones

### ISSUE THREAD

**Issue by flipactual** [marnusw/date-fns-tz#19]
I've been chasing down a bug where we're passing in poorly formatted timezones to `date-fns-tz` and noticed that I can provide `utcToZonedTime` with imaginary time zones and still get a result back

```
> utcToZonedTime(Date.now(), 'America/Chicago')
2019-06-12T22:33:56.000Z
> utcToZonedTime(Date.now(), 'America/Hello, date-fns-tz!')
2019-06-13T03:34:15.000Z
> utcToZonedTime(Date.now(), 'What is happening?')
2019-06-13T03:36:23.000Z

```

Is this behavior intentional?

**Comment by marnusw** [comment]
It is not intentional, and I can't say what it's doing behind the scenes without looking at the code again. The library itself doesn't actually do anything with the time zone value, it is just passed to the underlying `Intl` API. That said, the `Intl` API will probably break on a bad time zone so something could be masking the error.

I'll take a look when I can. It might not be too soon, but it seems like a good idea to handle this better.

**Comment by MrAlexLau** [comment]
@flipactual - to expand on the answer above, this library does indeed call `Intl.DateTimeFormat`. Here's the [exact line in the source](https://github.com/marnusw/date-fns-tz/blob/1d871f2c7ca76733552d5e22371a5fedcbe3c49f/src/_lib/tzTokenizeDate/index.js#L46-L48).

If you look at the [MDN documentation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DateTimeFormat#Browser_compatibility) for Intl.DateTimeFormat, most browsers support the [IANA](https://www.iana.org/time-zones) timezone format. However the documentation also notes:

> The only value implementations must recognize is "UTC"; the default is the runtime's default time zone. Implementations may also recognize the time zone names of the IANA time zone database, such as "Asia/Shanghai", "Asia/Kolkata", "America/New_York".

**Comment by marnusw** [comment]
Since the `Intl` spec specifies using the runtime's default time zone when the provided time zone is not recognised I don't think there is anything left to do here. The purpose of this library is to support time zone handling using the `Intl` API, so it seems fair that its policy for invalid time zones should be the same.
