### ISSUE TITLE
ISO-8601 With offset displaying local time

### ISSUE THREAD

**Issue by bringking** [marnusw/date-fns-tz#40]
I have been struggling with an ISO 8601 date string that we need to display and perserve the offset (_not_ display it in the users local time). Here is the input in ISO-8601 format-

_Source_
`2020-01-09T20:00-05:00`

_Formatting_
```
import { toDate, format } from 'date-fns-tz';
const dateWithTz = toDate('2020-01-09T20:00-05:00');
const formatted = format(dateWithTz, ' hh:mm a - eeee, MMMM d, yyyy');
```

_result_
`06:00 PM - Thursday, January 9, 2020 // my local time` 

_expected_
`08:00 PM - Thursday, January 9, 2020 // the correct time in the specified offset`

Am I missing a step here?

**Comment by marnusw** [comment]
It's an interesting one. These are the steps currently required:

1. `toDate` parses the string taking the offset into account and giving the correct timestamp, i.e. the UTC time you're looking for.
2. Use `utcToZoneTime(dateWithTz, timeZone)` to effectively indicate for which time zone you want to format.
3. `format(dateWithTz, ' hh:mm a - eeee, MMMM d, yyyy')` to display for that time zone.

Whenever I've used this / thought about it the time zone to display for was available as an IANA time zone string. In your case it's not, because it's contained in the original date string.

I **think** `utcToZoneTime` might work with offsets as well as IANA time zones, so you could try slicing it off the date in order to call this. Granted it's a bit messy though.

I won't have time to think about this right now, but if you can figure it out and if necessary propose a PR I'll find time to consider it.

**Comment by bringking** [comment]
@marnusw so using the offset worked as intended, but I had to extract it from the ISO String like so 

```js
import { toDate, format, utcToZonedTime } from 'date-fns-tz';

const isoDateString = '2020-01-09T20:00-05:00';
const dateWithTz = toDate(isoDateString);
const [offset] = isoDateString.match(/(-|\+)([0-9][0-9]):([0-9][0-9])$/);
const timeZonedDate = utcToZonedTime(dateWithTz, offset);
format(timeZonedStartDate, 'eeee, MMMM d, yyyy', { timeZone: offset })
```

I will close this since it's technically possible, but have to jump through hoops. If there is a better way, would be interested to know it.
