### ISSUE TITLE
try to convert the current date to utc time. failed 

### ISSUE THREAD

**Issue by RyanZhu1024** [marnusw/date-fns-tz#95]
`zonedTimeToUtc(new Date(), Intl.DateTimeFormat().resolvedOptions().timeZone)` returns the same date as `new Date()`
 while I'm expecting to have the UTC date.

**Comment by aswinsekar** [comment]
I think that is expected result.

Correct me, if I am wrong. 
_zonedTimeToUtc_ will give you a date instance and _new Date()_ will give you the instance containing same value. Because, both these represents a same single moment in time. To make my statement clear, read the [Date](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date) object MDN Docs. It is an representation of a single moment in time in a platform-independent format. Date objects contain a Number that represents milliseconds since 1 January 1970 UTC.

Trust me, it is little difficult to wrap the head around this Date and timezone. Perhaps, it will be easy to help, if you explain your use case, or what you are trying to achieve.

**Comment by linotex** [comment]
Hey! 
I have the same problem
@aswinsekar, I understand what happening, but how can I resolve this issue?
How can I avoid use standard date functions (getUTCHour) when I am usinf date0fns-tz?

**Comment by aswinsekar** [comment]
> Hey!
> I have the same problem
> @aswinsekar, I understand whats happening, but how can I resolve this issue?
> How can I avoid use standard date functions (getUTCHour) when I am using date-fns-tz?

Why you want to avoid use standard date functions, when using date-fns-tz? You can use it. date-fns-tz returns a valid date instance for timzone conversion utils. Please, give an sample snippet of what you are trying and what is you are expecting as result, so that community can help 😄 .

**Comment by linotex** [comment]
Hey!


> > Hey!
> > I have the same problem
> > @aswinsekar, I understand whats happening, but how can I resolve this issue?
> > How can I avoid use standard date functions (getUTCHour) when I am using date-fns-tz?
> 
> Why you want to avoid use standard date functions, when using date-fns-tz? You can use it. date-fns-tz returns a valid date instance for timzone conversion utils. Please, give an sample snippet of what you are trying and what is you are expecting as result, so that community can help 😄 .

Hey!
I wanted to have one place to work with dates))) But dont worry, I started to use getUTC functions )))
